/**
 * @see https://www.fantasynamegenerators.com/fantasy-town-names.php
 * I just hit that website a bunch and grabbed whatever it said
 */
export enum Towns {
  Brightwater = "Brightwater",
  Honeymoor = "Honeymoor",
  Eastshield = "Eastshield",
  Graymeadow = "Graymeadow",
  Limestorm = "Limestorm",
  Hollowgarde = "Hollowgarde",
  Lightfell = "Lightfell",
  Stonepeak = "Stonepeak",
  Emberspell = "Emberspell",
  Ambertide = "Ambertide",
  Chillstar = "Chillstar",
  Timbershade = "Timbershade",
  Scorchhill = "Scorchhill",
  Southacre = "Southacre",
  Bronzedenn = "Bronzedenn",
  Heartland = "Heartland",
  Autumnview = "Autumnview",
  Lakewich = "Lakewich",
  Elderminster = "Elderminster",
  Smallgrasp = "Smallgrasp",
  Rosebell = "Rosebell",
  Rockband = "Rockband",
  Icefield = "Icefield",
  Neverfall = "Neverfall",
  Rimekeep = "Rimekeep",
  Ghostfall = "Ghostfall",
  Diregarde = "Diregarde",
  Quickfall = "Quickfall",
  Mythham = "Mythham",
  Bridgekeep = "Bridgekeep",
  Sunfront = "Sunfront",
}

export const townConfig = [
  Towns.Brightwater,
  Towns.Honeymoor,
  Towns.Eastshield,
  Towns.Graymeadow,
  Towns.Limestorm,
  Towns.Hollowgarde,
  Towns.Lightfell,
  Towns.Stonepeak,
  Towns.Emberspell,
  Towns.Ambertide,
  Towns.Chillstar,
  Towns.Timbershade,
  Towns.Scorchhill,
  Towns.Southacre,
  Towns.Bronzedenn,
  Towns.Heartland,
  Towns.Autumnview,
  Towns.Lakewich,
  Towns.Elderminster,
  Towns.Smallgrasp,
  Towns.Rosebell,
  Towns.Rockband,
  Towns.Icefield,
  Towns.Neverfall,
  Towns.Rimekeep,
  Towns.Ghostfall,
  Towns.Diregarde,
  Towns.Quickfall,
  Towns.Mythham,
  Towns.Bridgekeep,
  Towns.Sunfront,
]
